change tests.yml

diff --git a/.github/workflows/tests.yml b/.github/workflows/tests.yml
--- a/.github/workflows/tests.yml
+++ b/.github/workflows/tests.yml
@@ -2,15 +2,19 @@ name: Tests
 
 on:
   push:
-    branches:
-      - main
+    branches: [ main ]
 
   pull_request:
-    branches:
-      - main
+    branches: [ main ]
 
 permissions:
-  contents: write
+  contents: read
+  pages: write
+  id-token: write
+
+concurrency:
+  group: pages
+  cancel-in-progress: true
 
 jobs:
   tests:
@@ -20,7 +24,7 @@ jobs:
       - name: Checkout repository
         uses: actions/checkout@v4
 
-      - name: Set up Python
+      - name: Setup Python
         uses: actions/setup-python@v5
         with:
           python-version: "3.12"
@@ -30,55 +34,48 @@ jobs:
           python -m pip install --upgrade pip
           pip install -r requirements.txt
 
-      - name: Start FastAPI server
+      - name: Start FastAPI
         run: |
           uvicorn app.main:app --host 127.0.0.1 --port 8000 &
           sleep 3
+
+      - name: Wait for server
+        run: |
+          for i in {1..30}; do
+            curl --fail http://127.0.0.1:8000/status && exit 0
+            sleep 1
+          done
+
+          echo "Server failed to start"
+          exit 1
 
       - name: Run tests
         run: |
           pytest -v --alluredir=allure-results
 
-      - name: Upload Allure Results
+      - name: Generate Allure report
+        uses: simple-elf/allure-report-action@v1.9
         if: always()
-        uses: actions/upload-artifact@v4
         with:
-          name: allure-results
-          path: allure-results
+          allure_results: allure-results
+          allure_report: allure-report
 
-  publish-allure:
-    needs: tests
+      - name: Upload GitHub Pages artifact
+        if: always()
+        uses: actions/upload-pages-artifact@v3
+        with:
+          path: allure-report
+
+  deploy:
     if: always()
+    needs: tests
 
     runs-on: ubuntu-latest
 
+    environment:
+      name: github-pages
+      url: ${{ steps.deployment.outputs.page_url }}
+
     steps:
-      - name: Checkout repository
-        uses: actions/checkout@v4
-
-      - name: Download Allure Results
-        uses: actions/download-artifact@v4
-        with:
-          name: allure-results
-          path: allure-results
-
-      - name: Get Allure history
-        continue-on-error: true
-        uses: actions/checkout@v4
-        with:
-          ref: gh-pages
-          path: gh-pages
-
-      - name: Generate Allure Report
-        uses: simple-elf/allure-report-action@v1.9
-        with:
-          allure_results: allure-results
-          allure_history: allure-history
-          gh_pages: gh-pages
-
-      - name: Publish report
-        uses: peaceiris/actions-gh-pages@v4
-        with:
-          github_token: ${{ secrets.GITHUB_TOKEN }}
-          publish_branch: gh-pages
-          publish_dir: allure-history
+      - id: deployment
+        uses: actions/deploy-pages@v4
